---
driver_plugin: digitalocean
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
  driver_plugin: digitalocean
  driver_config:
    image_id: 562354
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>

suites:
  - name: default
    run_list:
      - recipe[now_test::default]
      - recipe[now_test::third]

